basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: 这是一个展示如何使用 ApiKeyAuth 的示例项目。
  title: Gin Swagger Example API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 返回 pong 消息，无需鉴权
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 心跳测试 (公开)
      tags:
      - Public
  /secure/data:
    get:
      consumes:
      - application/json
      description: 需要提供 Header 中的 Authorization 才能访问
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: 获取私密数据 (受保护)
      tags:
      - Secure
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  AppKeyAuth:
    in: header
    name: X-APP-KEY
    type: apiKey
  AppSecretAuth:
    in: header
    name: X-APP-SECRET
    type: apiKey
swagger: "2.0"
